#ifndef API_H
#define API_H

#define CRYPTO_KEYBYTES 16
#define CRYPTO_NSECBYTES 0
#define CRYPTO_NPUBBYTES 16
#define CRYPTO_ABYTES 16
#define CRYPTO_NOOVERLAP 1


// #define REFERENCE_LENGTH


// #define MULTIROUND

#define CRYPTO_AEAD_ENCRYPT_ASM_BIG_ENDIAN 0
#define CRYPTO_AEAD_ENCRYPT_ASM_LITTLE_ENDIAN 1
#define CRYPTO_AEAD_ENCRYPT_C_HW 2
#define CRYPTO_AEAD_ENCRYPT_C_SW 3
#define CRYPTO_AEAD_ENCRYPT_C_BIT_INTERLEAVED 4

#define CRYPTO_HASH_C_SW 5
#define CRYPTO_HASH_C_HW 6
#define CRYPTO_HASH_ASM_BIG_ENDIAN 7
#define CRYPTO_HASH_ASM_LITTLE_ENDIAN 8

#ifndef MULTIROUND_CONF
	#define MULTIROUND_CONF 1
#endif

#ifndef LITTLE_ENDIAN_CONF
	#define LITTLE_ENDIAN_CONF 1
#endif

#ifndef SPIKE
	#ifndef RISCY_HIGH_PERFORMANCE
		#define RISCY_HIGH_PERFORMANCE 1
	#endif
#else
	#undef RISCY_HIGH_PERFORMANCE
#endif

#ifndef PERFORMANCE_TEST
	#define PERFORMANCE_TEST 1
#endif

#ifndef IMPLEMENTATION_CHOICE
	#if (ASCON_INSTR == 1)
		#if (LITTLE_ENDIAN_CONF == 1)
			#define IMPLEMENTATION_CHOICE CRYPTO_AEAD_ENCRYPT_ASM_LITTLE_ENDIAN
		#else
			#define IMPLEMENTATION_CHOICE CRYPTO_AEAD_ENCRYPT_ASM_BIG_ENDIAN
		#endif
	#elif (ASCON_INSTR == 2)
		#define IMPLEMENTATION_CHOICE CRYPTO_AEAD_ENCRYPT_C_HW
		#undef LITTLE_ENDIAN_CONF
		#define LITTLE_ENDIAN_CONF 0
	#else
		#define IMPLEMENTATION_CHOICE CRYPTO_AEAD_ENCRYPT_C_SW
	#endif
#endif


// The hardware can only run either in little or big endian mode
#ifdef SPIKE
	#define NUM_BENCHMARKFUNCTIONS 4
#else
	#define NUM_BENCHMARKFUNCTIONS 1
// #if (LITTLE_ENDIAN_CONF == 1)
// 	#define NUM_BENCHMARKFUNCTIONS 2
// #else
// 	#define NUM_BENCHMARKFUNCTIONS 3
// #endif	
#endif

// Settings for performance and performance hashing evaluation
#ifndef MIN_ASSOCIATED_DATA_LENGTH
	#define MIN_ASSOCIATED_DATA_LENGTH	0
#endif
#ifndef STEP_ASSOCIATED_DATA
	#define STEP_ASSOCIATED_DATA				64
#endif
#ifndef MAX_ASSOCIATED_DATA_LENGTH
	#define MAX_ASSOCIATED_DATA_LENGTH	0
#endif

#ifndef MIN_MESSAGE_LENGTH
	#define MIN_MESSAGE_LENGTH					0
#endif
#ifndef STEP_MESSAGE
	#define STEP_MESSAGE								64
#endif
#ifndef MAX_MESSAGE_LENGTH
	#define MAX_MESSAGE_LENGTH					512
#endif

#define ALIVE_MESSAGE_INTERVAL      5000

#endif
